name: Build, Obfuscate and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Déclenche le build à chaque push sur la branche main

# Indique à GitHub d'accorder les permissions nécessaires pour Pages et l'authentification (OIDC)
permissions:
  contents: read
  pages: write
  id-token: write

# Permet d'annuler les builds précédents si un nouveau push est fait entre-temps
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupérer le code
        uses: actions/checkout@v4

      - name: ⚙️ Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Installer les dépendances du build
        run: npm install cheerio terser

      - name: 🚀 Lancer le script de build
        run: node build.js

      - name: 🎛️ Configurer Pages
        uses: actions/configure-pages@v5

      - name: 📤 Upload du dossier dist vers GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # On indique à GitHub d'uploader le dossier produit par ton script Node
          path: 'dist/'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps:https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site }}
    runs-on: ubuntu-latest
    needs: build # On attend que l'étape de build soit terminée avec succès
    
    steps:
      - name: 🚀 Déploiement sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
